### ISSUE TITLE
Support Julia 1.6 (and lower?)

### ISSUE THREAD

**Issue by sonosole** [pc2/GPUInspector.jl#3]
It's a really nice pkg, but would you plz add more versions to make it more compatible. 
I think that a lot of users are now using julia1.0~julia1.6 versions. Thanks :)

**Comment by carstenbauer** [comment]
Hey there!

Thanks for the suggestions. We can certainly try to provide some features for lower Julia versions. However, for the peakflops tools we rely on a recent version of LLVM etc. and therefore a modern Julia version. (Actually, to test Float64 WMMAs on Tensor Cores Julia 1.7 isn't even enough but we need Julia 1.8 or later.)

Also note that we likely won't support Julia < 1.6 because 1.6 is the current LTS and people using older Julia versions should seriously consider upgrading to 1.6.)

Best,
Carsten

**Comment by carstenbauer** [comment]
We provide initial 1.6 support (as far as possible) from version 0.2.0 on (will release it later today).
